### ISSUE TITLE
[resolved]

### ISSUE THREAD

**Issue by WeiChiaChang** [acupoftee/OverwatchLeagueGO#5]
[resolved]

**Comment by acupoftee** [comment]
@WeiChiaChang Hi Wei. Thank you for your issue. I can assure you that that everything was built ethically. Attribution was a huge oversight and I apologize for not doing it properly. I tried to redesign everything to the best of my ability and will continue to do so. It was an oversight on my part as my original intentions were not to release this publicly, but to build it for my own enrichment.

I've noticed you built a project which was very similar to Lydia Hallie's work, but you did included an attribution. I have linked Homey's work as well. I am new to frontend, and the file structure is what made sense when building OWL Bar, but with practice I have gotten comfortable using file structures that are intuitive to me.

Here's the attribution I've included in this repo and OWL Bar. I hope I've cleared up any misunderstandings. These were truly projects I was inspired by and my intentions were to simply learn from them. My sincerest apologies for any misunderstandings. 

<img width="964" alt="Screen Shot 2020-03-21 at 11 45 49 AM" src="https://user-images.githubusercontent.com/15068267/77230307-a740c780-6b69-11ea-9ba0-e25268eba573.png">

**Comment by acupoftee** [comment]
Here's the attribution I've included in this repo and OWL Bar. I hope I've cleared up any misunderstandings. These were truly projects I was inspired by and my intentions were to simply learn from them. My sincerest apologies. 

<img width="964" alt="Screen Shot 2020-03-21 at 11 45 49 AM" src="https://user-images.githubusercontent.com/15068267/77230307-a740c780-6b69-11ea-9ba0-e25268eba573.png">

**Comment by Bitchrovert** [comment]
Geez, that guy's an asshole #chinesevirus

**Comment by WeiChiaChang** [comment]
Hello @acupoftee 

I'm sorry for this issue that cause a lot of misunderstanding.
And I've DM to you via private message on Twitter this Monday, please check it thank you.

Besides, I do really like your projects which on GitHub & Codepen. The pure css arts series really amazing. To be honest, I also eager to have a chance to cooperate with you on an open-source project someday. 

@Bitchrovert COVID-19 is really a SERIOUS worldwide issue. Please take care.
